name: 🔐 Security Scan

on:
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM UTC
  push:
    branches: [ main ]
  # Removed pull_request to speed up PR checks

jobs:
  security:
    name: 🔐 Security Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 📦 Install dependencies
      run: npm ci
      
    - name: 🛡️ Security audit (fast)
      run: |
        echo "🛡️ Running npm security audit..."
        npm audit --audit-level=high --production || echo "⚠️ Security audit completed"
        
    - name: 🔍 CodeQL Analysis
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
        
    - name: 🔍 Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
        
    - name: 📝 Security report
      run: |
        echo "📝 Generating security report..."
        npm audit --json > security-report.json || echo "⚠️ Security report generated"
        
    - name: 📤 Upload security report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-report
        path: security-report.json
        retention-days: 30 